# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4db48e834d77d49bc3004a96574f599f503608889855beec712146531272d204d6249e0e1428d6e49bb6b426bfd46b29dc5455811c1be56b83548c707b258b75

test:
  secret_key_base: a323eb61bd7d57a99340c97685e464fc2b03938f96a602d64e220de9ad81caa54550076c403814e281df11cc9ce4fa42409c1f77f6709df6cc8f8cf4869e57bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
